# Generated by Django 2.1.2 on 2019-05-03 14:01

import datetime
from django.db import migrations, models
import imageserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='date_in_database',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=imageserver.models.image_path, validators=[imageserver.models.validate_image]),
        ),
    ]
