# Generated by Django 2.1.2 on 2019-05-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0003_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='type',
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
